apiVersion: v2
name: kyverno-crds
description: This app contains the Kyverno CRDs.
home: https://github.com/giantswarm/kyverno-crds
icon: https://s.giantswarm.io/app-icons/kyverno/1/light.svg
sources:
  - https://github.com/kyverno/kyverno
version: 1.16.0
annotations:
  application.giantswarm.io/team: shield
dependencies:
  - name: crds
    version: 3.7.0
  - name: kyverno-api
    version: 0.0.0
